project:
  type: website

website:
  title: "ISSS608_AY2022-23_April_YeNaingOo"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: Inclass_ex04.qmd
        text: Inclass_ex04

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual