
project:
  type: website

website:
  title: "ISSS608 Ye Naing Oo"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "In Class Exercises"
        file: Inclass_ex04.qmd
      - text: "Take Home Exercises"
        file: Take-home-Exercise_1.qmd
      - text: "Visual Analytics Project"
        file: index.qmd

  
  sidebar:
    - title: "In Class Exercises"
      style: "docked"
      background: light
      tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/naingoo-ye/
      - icon: github
        href: https://github.com/noye09    
      contents:
        - Inclass_ex04.qmd
        - Inclass_ex05.qmd
        - MC1.qmd
        
    - title: "Take Home Exercises"
      contents:
        - Take-home-Exercise_1.qmd
        - Take-home-Exercise_2.qmd
        - Take-home-Exercise_3.qmd
        # navigation items
        
  


format:
  html:
    grid:
      body-width: 1200px
    theme: Flatly
    css: styles.css
    toc: true
    code-fold: true
    code-summary: "Show the code"
    navbar: true
  
editor: visual
    